Add integration test (#112)
* Check run_integration_tests

* Add branch to run_integration_tests

* Pass command for CI

* Check curl for run_integration_tests

* Refine wait url

* Rerun run_integration_tests

* Set port testit

* Refine rule for testit

* Try with no wait for testit

* Try renaming

* Just run testit

* Try what AI says

* Try rule for integration tests

* Run tests on branch

* Add db dsn

* Set postgress pvd

* Set DB

* Load config from file

* Build on github

* Move kodata to right place

* Remove timeout in test request

* Rename config

* Try sync

* Add enricher config

* Add enricher file

* Fix package

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -10,6 +10,7 @@ on:
     - PH-89/*
     - PH-92/*
     - PH-94/*
+    - PH-38/*
     tags:
     - 'v*'
   pull_request:
@@ -78,7 +79,7 @@ jobs:
     secrets: inherit
   
   get-version:
-    if: github.event.inputs.run_integration_tests == 'true' || contains(github.event.head_commit.message, 'run_integration_tests')
+    if: github.event.inputs.run_integration_tests == 'true' || contains(github.event.head_commit.message, 'testit') || contains(github.event.head_commit.message, 'testbe') || contains(github.ref, 'integration-test')
     runs-on: ubuntu-latest
     outputs:
       version: ${{ steps.version.outputs.version }}
@@ -97,7 +98,125 @@ jobs:
           echo "Using version: $VERSION"
 
   integration-test:
-    if: github.event.inputs.run_integration_tests == 'true' || contains(github.event.head_commit.message, 'run_integration_tests')
+    if: github.event.inputs.run_integration_tests == 'true' || contains(github.event.head_commit.message, 'testit') || contains(github.ref, 'integration-test')
+    needs: [get-version, ko-build]
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read # Required for checkout
+      packages: read # Required to pull images from GHCR
+    services:
+      redis:
+        image: redis:6.2-alpine
+        ports:
+          - 6379:6379
+        options: >-
+          --health-cmd "redis-cli ping"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+
+      postgres:
+        image: postgres:15-alpine
+        ports:
+          - 5432:5432
+        options: >-
+          --health-cmd "pg_isready -U postgres"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+        env:
+          POSTGRES_DB: pharos
+          POSTGRES_USER: postgres          
+          POSTGRES_PASSWORD: postgres
+
+      scanner:
+        # The image is tagged with the version from semver.sh
+        image: ghcr.io/metraction/pharos/pharos-c52785725d1132c2f91e01422b7f40ba:${{ needs.get-version.outputs.version }}
+        env:
+          PHAROS_REDIS_DSN: redis:6379
+          PHAROS_SCANNER_CACHEENDPOINT: redis://redis:6379
+
+      publisher:
+        # The image is tagged with the version from semver.sh
+        image: ghcr.io/metraction/pharos/pharos-c52785725d1132c2f91e01422b7f40ba:${{ needs.get-version.outputs.version }}
+        ports:
+          - 8080:8080
+        env:
+          PHAROS_REDIS_DSN: redis:6379
+          PHAROS_SCANNER_CACHEENDPOINT: redis://redis:6379
+          PHAROS_DATABASE_DSN: postgres://postgres:postgres@postgres:5432/pharos?sslmode=disable
+          PHAROS_COMMAND: http
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: '1.23' 
+
+      - name: Wait for services to be healthy
+        run: |
+          echo "Waiting for services to initialize..."
+          sleep 15 # Adjust as needed, or implement a more robust health check for the scanner
+
+      - name: Run http integration tests
+        run: |
+          # # Wait for HTTP service to be ready
+          echo "Waiting for HTTP service to be available..."
+          timeout 15 bash -c 'until curl -s http://localhost:8080/api/docs; do sleep 1; done'
+          
+          # Send request and capture response
+          echo "Sending test request to API..."
+          response=$(curl -s -w "\n%{http_code}" -X POST http://localhost:8080/api/pharosscantask/syncscan \
+            -H "Content-Type: application/json" \
+            -d '{
+              "jobId": "2",
+              "status": "",
+              "engine": "",
+              "error": "",
+              "authdsn": "registry:///?tlscheck=false",
+              "imagespec": "rancher/nginx-ingress-controller:nginx-1.11.3-rancher1",
+              "platform": "linux/amd64",
+              "context": {
+                "namespace": "ingress-nginx"
+              },
+              "contextRootKey": "namespace=ingress-nginx,",
+              "rxdigest": "",
+              "rxplatform": "",
+              "cachettl": 0,
+              "scanttl": 60000000000,
+              "created": "2025-07-02T10:20:35.784021+02:00",
+              "updated": "2025-07-02T10:20:35.784021+02:00"
+            }')
+          
+          # Extract status code
+          status_code=$(echo "$response" | tail -n1)
+          response_body=$(echo "$response" | sed '$d')
+          
+          # Check if request was successful
+          echo "Response body: $response_body"
+          echo "Status code: $status_code"
+          
+          if [[ "$status_code" -ge 200 && "$status_code" -lt 300 ]]; then
+            echo "HTTP request successful"
+          else
+            echo "HTTP request failed with status $status_code"
+            exit 1
+          fi
+
+      - name: Run controller integration tests
+        env:
+          DATABASE_DSN: "postgres://postgres:postgres@localhost:5432?sslmode=disable"
+          DATABASE_DRIVER: "postgres"
+        run: |
+          go test ./internal/controllers -timeout=5m -v
+
+  benchmark-test:
+    if: github.event.inputs.run_benchmark_tests == 'true' || contains(github.event.head_commit.message, 'testbe')
     needs: [get-version, ko-build]
     runs-on: ubuntu-latest
     permissions:
@@ -148,13 +267,6 @@ jobs:
         run: |
           echo "Waiting for services to initialize..."
           sleep 15 # Adjust as needed, or implement a more robust health check for the scanner
-
-      - name: Run controller integration tests
-        env:
-          DATABASE_DSN: "postgres://postgres:postgres@localhost:5432?sslmode=disable"
-          DATABASE_DRIVER: "postgres"
-        run: |
-          go test ./internal/controllers -timeout=5m -v
 
       - name: Run benchmark tests
         env:
